### ISSUE TITLE
Cython.Compiler.Errors.CompileError: pyflow.pyx

### ISSUE THREAD

**Issue by Marchong** [pathak22/pyflow#1]
first ，thank you for your work !
I want to use this pyflow work alone,but when i run `python setup.py build_ext -i` ,it make some wrong like this:
```
Compiling pyflow.pyx because it changed.
Cythonizing pyflow.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    void Coarse2FineFlowWrapper(double * vx, double * vy, double * warpI2,
                                  const double * Im1, const double * Im2,
                                  double alpha, double ratio, int minWidth,
                                  int nOuterFPIterations, int nInnerFPIterations,
                                  int nSORIterations, int colType,
                                  int h, int w, int c);
                                                     ^
------------------------------------------------------------

pyflow.pyx:17:54: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    ext_modules=cythonize(extensions),
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pyflow.pyx
```
Can you give me some suggestion on this problem ？Thank you .

**Comment by Marchong** [comment]
I had try some ways to resolve it ,but didn't work .Looking forward to your reply .

**Comment by Marchong** [comment]
I try to del the `;`behind the code below:
```
    void Coarse2FineFlowWrapper(double * vx, double * vy, double * warpI2,
                                  const double * Im1, const double * Im2,
                                  double alpha, double ratio, int minWidth,
                                  int nOuterFPIterations, int nInnerFPIterations,
                                  int nSORIterations, int colType,
                                  int h, int w, int c);
```
it seem to work with these:
`Compiling pyflow.pyx because it changed.
Cythonizing pyflow.pyx
running build_ext
building 'pyflow' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pyflow.cpp -o build/temp.linux-x86_64-2.7/pyflow.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from pyflow.cpp:352:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/include/python2.7/numpy/ndarrayobject.h:26:0,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from pyflow.cpp:352:
/usr/include/python2.7/numpy/__multiarray_api.h:1629:1: warning: ‘int _import_array()’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
In file included from /usr/include/python2.7/numpy/ufuncobject.h:327:0,
                 from pyflow.cpp:353:
/usr/include/python2.7/numpy/__ufunc_api.h:241:1: warning: ‘int _import_umath()’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/OpticalFlow.cpp -o build/temp.linux-x86_64-2.7/src/OpticalFlow.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
src/OpticalFlow.cpp: In static member function ‘static void OpticalFlow::SmoothFlowSOR(const DImage&, const DImage&, DImage&, DImage&, DImage&, double, int, int, int)’:
src/OpticalFlow.cpp:267:11: warning: unused variable ‘power_alpha’ [-Wunused-variable]
    double power_alpha = 0.5;
           ^
src/OpticalFlow.cpp:287:11: warning: unused variable ‘_a’ [-Wunused-variable]
    double _a  = 10000, _b = 0.1;
           ^
src/OpticalFlow.cpp:287:24: warning: unused variable ‘_b’ [-Wunused-variable]
    double _a  = 10000, _b = 0.1;
                        ^
src/OpticalFlow.cpp: In static member function ‘static void OpticalFlow::SmoothFlowPDE(const DImage&, const DImage&, DImage&, DImage&, DImage&, double, int, int, int)’:
src/OpticalFlow.cpp:545:11: warning: unused variable ‘power_alpha’ [-Wunused-variable]
    double power_alpha = 0.5;
           ^
src/OpticalFlow.cpp:565:11: warning: unused variable ‘_a’ [-Wunused-variable]
    double _a  = 10000, _b = 0.1;
           ^
src/OpticalFlow.cpp:565:24: warning: unused variable ‘_b’ [-Wunused-variable]
    double _a  = 10000, _b = 0.1;
                        ^
In file included from src/Image.h:9:0,
                 from src/OpticalFlow.h:6,
                 from src/OpticalFlow.cpp:4:
src/ImageProcessing.h: In instantiation of ‘static void ImageProcessing::vfiltering(const T1*, T2*, int, int, int, const double*, int) [with T1 = double; T2 = double]’:
src/Image.h:1331:96:   required from ‘void Image<T>::imfilter_hv(Image<T1>&, const double*, int, const double*, int) const [with T1 = double; T = double]’
src/OpticalFlow.cpp:52:42:   required from here
src/ImageProcessing.h:344:14: warning: unused variable ‘offset’ [-Wunused-variable]
  int i,j,l,k,offset,ii;
              ^
In file included from src/OpticalFlow.h:6:0,
                 from src/OpticalFlow.cpp:4:
src/Image.h: In instantiation of ‘void Image<T>::warpImageBicubicRef(const Image<T>&, Image<T>&, const Image<T1>&, const Image<T1>&, const Image<T1>&, const Image<T2>&, const Image<T2>&) const [with T1 = double; T2 = double; T = double]’:
src/Image.h:2482:55:   required from ‘void Image<T>::warpImageBicubicRef(const Image<T>&, Image<T>&, const Image<T1>&, const Image<T1>&) const [with T1 = double; T = double]’
src/OpticalFlow.cpp:437:43:   required from here
src/Image.h:2525:4: warning: variable ‘ImgMax’ set but not used [-Wunused-but-set-variable]
  T ImgMax;
    ^
In file included from /usr/include/string.h:640:0,
                 from /usr/include/memory.h:29,
                 from src/Image.h:8,
                 from src/OpticalFlow.h:6,
                 from src/OpticalFlow.cpp:4:
In function ‘void* memset(void*, int, size_t)’,
    inlined from ‘static void ImageProcessing::ResizeImage(const T1*, T2*, int, int, int, int, int) [with T1 = double; T2 = double]’ at src/ImageProcessing.h:230:2:
/usr/include/x86_64-linux-gnu/bits/string3.h:81:32: warning: call to ‘__warn_memset_zero_len’ declared with attribute warning: memset used with constant zero length parameter; this could be due to transposed parameters [enabled by default]
       __warn_memset_zero_len ();
                                ^
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/Stochastic.cpp -o build/temp.linux-x86_64-2.7/src/Stochastic.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/GaussianPyramid.cpp -o build/temp.linux-x86_64-2.7/src/GaussianPyramid.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from src/Image.h:9:0,
                 from src/GaussianPyramid.h:7,
                 from src/GaussianPyramid.cpp:4:
src/ImageProcessing.h: In instantiation of ‘static void ImageProcessing::vfiltering(const T1*, T2*, int, int, int, const double*, int) [with T1 = double; T2 = double]’:
src/Image.h:1331:96:   required from ‘void Image<T>::imfilter_hv(Image<T1>&, const double*, int, const double*, int) const [with T1 = double; T = double]’
src/Image.h:1199:47:   required from ‘void Image<T>::GaussianSmoothing(Image<T1>&, double, int) const [with T1 = double; T = double]’
src/GaussianPyramid.cpp:67:45:   required from here
src/ImageProcessing.h:344:14: warning: unused variable ‘offset’ [-Wunused-variable]
  int i,j,l,k,offset,ii;
              ^
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/Coarse2FineFlowWrapper.cpp -o build/temp.linux-x86_64-2.7/src/Coarse2FineFlowWrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pyflow.o build/temp.linux-x86_64-2.7/src/OpticalFlow.o build/temp.linux-x86_64-2.7/src/Stochastic.o build/temp.linux-x86_64-2.7/src/GaussianPyramid.o build/temp.linux-x86_64-2.7/src/Coarse2FineFlowWrapper.o -o /home/zhou/pyflow/pyflow.so
build/temp.linux-x86_64-2.7/src/OpticalFlow.o：在函数‘memset’中：
/usr/include/x86_64-linux-gnu/bits/string3.h:81: 警告： memset used with constant zero length parameter; this could be due to transposed parameters
`
and then i run `python demo.py ` :+1: 
`Constructing pyramid...done!
Pyramid level 11
Pyramid level 10
Pyramid level 9
Pyramid level 8
Pyramid level 7
Pyramid level 6
Pyramid level 5
Pyramid level 4
Pyramid level 3
Pyramid level 2
Pyramid level 1
Pyramid level 0
Time Taken: 4.35 seconds for image of size (480, 640, 3)
`
Does it means it was worked well without problems?

**Comment by pathak22** [comment]
If it outputs the flow image and it matches the one given in the repository, then I suppose it worked. Not sure what's up with semicolon. Could it be a cython version thing ?

**Comment by Marchong** [comment]
I guess so， I did this cause i see an introduction about the cython programming which no [；] behind the  Function declaration .Thank you for your reply !

**Comment by Marchong** [comment]
Hi ，I just want to ask another question: Did you try use CUDA to faster the optical flow method ?

**Comment by Zechr** [comment]
Thanks for making this. I really want to use this for a computer vision project. When I try the python setup.py build_ext -i command, it tells me Unable to find vcvarsall.bat. Is this a known bug or is it specific to my machine (windows)?

**Comment by pathak22** [comment]
@Marchong Sorry, I have not tried to use CUDA. But feel free to do a pull request if you happen to try it. :)

@Zechr  Sorry, I have not tested it on windows -- but this looks like it needs some library in windows?
