### ISSUE TITLE
how to disable logging from pyflow?

### ISSUE THREAD

**Issue by eisneim** [pathak22/pyflow#32]
```
Constructing pyramid...done!
Pyramid level 7
Pyramid level 6
Pyramid level 5
Pyramid level 4
Pyramid level 3
Pyramid level 2
Pyramid level 1
Pyramid level 0
```
i tried replace `replace sys.stdout` or contextlib.redirect_stdout it's not working

**Comment by lolikonloli** [comment]
in file src/OpticalFlow.cpp
#ifndef _MATLAB
	bool OpticalFlow::IsDisplay=true;
#else
	bool OpticalFlow::IsDisplay=false;
#endif

change true to false and then rebuild and reinstall
