### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by adizhol** [pathak22/pyflow#4]
Hello,

I'm trying to setup (compile) the source on Windows 10 with VC++ 14, python 3.5 but I get the following error(s)

`running build_ext
building 'pyflow' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Adi\Miniconda3\envs\python35\lib\site-packages\numpy\core\include -IC:\Users\Adi\Miniconda3\envs\python35\lib\site-packages\numpy\core\include -IC:\Users\Adi\Miniconda3\envs\python35\include -IC:\Users\Adi\Miniconda3\envs\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tppyflow.cpp /Fobuild\temp.win-amd64-3.5\Release\pyflow.obj
pyflow.cpp
c:\users\adi\miniconda3\envs\python35\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pyflow.cpp(1949): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
pyflow.cpp(1958): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
pyflow.cpp(1967): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Adi\Miniconda3\envs\python35\lib\site-packages\numpy\core\include -IC:\Users\Adi\Miniconda3\envs\python35\lib\site-packages\numpy\core\include -IC:\Users\Adi\Miniconda3\envs\python35\include -IC:\Users\Adi\Miniconda3\envs\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpsrc\Coarse2FineFlowWrapper.cpp /Fobuild\temp.win-amd64-3.5\Release\src\Coarse2FineFlowWrapper.obj
Coarse2FineFlowWrapper.cpp
d:\pyflow\src\project.h(41): error C2146: syntax error: missing ')' before identifier 'a'
d:\pyflow\src\project.h(41): error C2365: 'T1': redefinition; previous definition was 'template parameter'
d:\pyflow\src\project.h(40): note: see declaration of 'T1'
d:\pyflow\src\project.h(41): error C2061: syntax error: identifier 'a'
d:\pyflow\src\project.h(41): error C2059: syntax error: ')'
d:\pyflow\src\project.h(41): error C2146: syntax error: missing ')' before identifier 'b'
d:\pyflow\src\project.h(41): error C2146: syntax error: missing ';' before identifier 'b'
d:\pyflow\src\project.h(42): error C2143: syntax error: missing ';' before '{'
d:\pyflow\src\project.h(42): error C2447: '{': missing function header (old-style formal list?)
d:\pyflow\src\project.h(47): error C2146: syntax error: missing ')' before identifier 'a'
d:\pyflow\src\project.h(47): error C2365: 'T1': redefinition; previous definition was 'template parameter'
d:\pyflow\src\project.h(46): note: see declaration of 'T1'
d:\pyflow\src\project.h(47): error C2061: syntax error: identifier 'a'
d:\pyflow\src\project.h(47): error C2059: syntax error: ')'
d:\pyflow\src\project.h(47): error C2146: syntax error: missing ')' before identifier 'b'
d:\pyflow\src\project.h(47): error C2146: syntax error: missing ';' before identifier 'b'
d:\pyflow\src\project.h(48): error C2143: syntax error: missing ';' before '{'
d:\pyflow\src\project.h(48): error C2447: '{': missing function header (old-style formal list?)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\vcruntime_typeinfo.h(110): error C2989: 'type_info': class template has already been declared as a non-class template
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\eh.h(49): note: see declaration of 'type_info'
d:\pyflow\src\ImageProcessing.h(130): error C2039: 'BilinearInterpolate': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(152): error C2039: 'BilinearInterpolate': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(179): error C2039: 'BilinearInterpolate_transpose': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(205): error C2039: 'ResizeImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(226): error C2039: 'ResizeImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(249): error C2039: 'hfiltering': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(274): error C2039: 'hfiltering_transpose': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(299): error C2039: 'Laplacian': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(339): error C2039: 'vfiltering': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(363): error C2039: 'vfiltering_transpose': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(390): error C2039: 'filtering': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(422): error C2039: 'filtering_transpose': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(450): error C2039: 'getPatch': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(471): error C2039: 'warpImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(493): error C2039: 'warpImageFlow': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(515): error C2039: 'warpImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(533): error C2039: 'warpImage_transpose': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(555): error C2039: 'warpImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(573): error C2039: 'warpImage_transpose': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(593): error C2039: 'warpImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(623): error C2039: 'cropImage': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(647): error C2039: 'generate2DGaussian': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(671): error C2039: 'generate1DGaussian': is not a member of 'ImageProcessing'
d:\pyflow\src\ImageProcessing.h(19): note: see declaration of 'ImageProcessing'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2`

**Comment by adizhol** [comment]
#1

**Comment by germunwang** [comment]
This should be the same problem as #7
