### ISSUE TITLE
error C2146: syntax error: missing ')' before identifier 'a'

### ISSUE THREAD

**Issue by IdoWSC** [pathak22/pyflow#7]
Hi, I'm trying to install the package according to the instructions and get the following:

C:\temp\pyflow>python setup.py build_ext -i
Compiling pyflow.pyx because it changed.
[1/1] Cythonizing pyflow.pyx
running build_ext
building 'pyflow' extension
creating build
creating build\temp.win-amd64-3.5
creating build\temp.win-amd64-3.5\Release
creating build\temp.win-amd64-3.5\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Anaconda3\lib\site-packages\numpy\core\include" "-IC:\Program Files\Anaconda3\lib\site-packages\numpy\core\include" "-IC:\Program Files\Anaconda3\include" "-IC:\Program Files\Anaconda3\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /EHsc /Tppyflow.cpp /Fobuild\temp.win-amd64-3.5\Release\pyflow.obj
pyflow.cpp
c:\program files\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pyflow.cpp(1594): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
pyflow.cpp(1603): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
pyflow.cpp(1612): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Anaconda3\lib\site-packages\numpy\core\include" "-IC:\Program Files\Anaconda3\lib\site-packages\numpy\core\include" "-IC:\Program Files\Anaconda3\include" "-IC:\Program Files\Anaconda3\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /EHsc /Tpsrc\Coarse2FineFlowWrapper.cpp /Fobuild\temp.win-amd64-3.5\Release\src\Coarse2FineFlowWrapper.obj
Coarse2FineFlowWrapper.cpp
c:\temp\pyflow\src\project.h(41): error C2146: syntax error: missing ')' before identifier 'a'
c:\temp\pyflow\src\project.h(41): error C2365: 'T1': redefinition; previous definition was 'template parameter'
c:\temp\pyflow\src\project.h(40): note: see declaration of 'T1'
c:\temp\pyflow\src\project.h(41): error C2061: syntax error: identifier 'a'
c:\temp\pyflow\src\project.h(41): error C2059: syntax error: ')'
c:\temp\pyflow\src\project.h(41): error C2146: syntax error: missing ')' before identifier 'b'
c:\temp\pyflow\src\project.h(41): error C2146: syntax error: missing ';' before identifier 'b'
c:\temp\pyflow\src\project.h(47): error C2146: syntax error: missing ')' before identifier 'b'
c:\temp\pyflow\src\project.h(47): error C2146: syntax error: missing ';' before identifier 'b'
c:\temp\pyflow\src\project.h(47): error C2059: syntax error: ')'
c:\temp\pyflow\src\project.h(48): error C2143: syntax error: missing ';' before '{'
c:\temp\pyflow\src\project.h(48): error C2447: '{': missing function header (old-style formal list?)
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime_typeinfo.h(108): error C2989: 'type_info': class template has already been declared as a non-class template
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\eh.h(49): note: see declaration of 'type_info'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by germunwang** [comment]
Hi, I just solved the same problem with you.

You need to uncomment a line of code in `src\project.h` Line 9 if compiling in Windows:

https://github.com/pathak22/pyflow/blob/994e29c77497de9798d77ed0f700807bf9b86ce3/src/project.h#L8-L9

I suggest that this setup comment should be added to README rather than source code.

**Comment by IdoWSC** [comment]
@germunwang  Thank you it solves the issue!
